server:
  port: 7001
spring:
#   profiles:
#     active: ${spring.profile}
  application:
    name: mobile-driver-licence
logging:
  level:
    root: DEBUG
mobile-doc:
  age-in-years: true
  age-birth-year: true
  age-over-nn: 16,19,60